# Generated by Django 4.2.4 on 2023-08-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('p_name',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
