# Generated by Django 4.2.4 on 2023-08-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('c_name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
