# Generated by Django 4.2.4 on 2023-09-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('p_name',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
