# Generated by Django 4.2.4 on 2023-09-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_version_product_alter_version_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='v_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='товар'),
        ),
    ]
