# Generated by Django 4.2.5 on 2023-09-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_version_v_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='v_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_version', to='catalog.product', verbose_name='товар'),
        ),
    ]
